version: '3.1'
services:
  taco-db:
    image: postgres:14-alpine

    ports:
      - "5442:5432"
    environment:
      - POSTGRES_DB=taco
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - taco-db:/var/data

volumes:
  taco-db: